image: Visual Studio 2017
version: 0.1-appveyor-{build}({branch})
before_build:
  - dir
  - ren ????????.sln HackerBomberScript.sln
  - nuget restore
configuration: Release
build:
  project: HackerBomberScript.sln
  verbosity: minimal
after_build: # build, copy files and pack
  - msbuild /p:Configuration=Release C:\projects\hackerbomberscript\HackerBomberCrossPlatform\HackerBomberCrossPlatform.csproj 
  - msbuild /t:SignAndroidPackage /p:Configuration=Release C:\projects\hackerbomberscript\MobileBomber\MobileBomber.csproj
  - md C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\ScriptInterpreter\bin\Release\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\HackerBomberApplication\bin\Release\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\HackerBomberCrossPlatform\bin\Release\netcoreapp2.1\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\BomberStudio\bin\Release\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\HackerBomber\bin\Release\*.* C:\projects\hackerbomberscript\binaries
  - copy C:\projects\hackerbomberscript\MobileBomber\bin\Release\*.* C:\projects\hackerbomberscript\binaries
  - del /q C:\projects\hackerbomberscript\binaries\*.pdb
  - del /q C:\projects\hackerbomberscript\binaries\*.mdb
  - del /q C:\projects\hackerbomberscript\binaries\*.config
  - del /q C:\projects\hackerbomberscript\binaries\*.json
  - del /q C:\projects\hackerbomberscript\binaries\com.companyname.mobilebomber.apk
  - ren C:\projects\hackerbomberscript\binaries\com.companyname.mobilebomber-Signed.apk com.companyname.mobilebomber.apk
  - 7z a -tzip final.zip .\binaries\*
artifacts:
  - path: final.zip
    name: Everything here
  - path: MobileBomber\bin\Release\com.companyname.mobilebomber-Signed.apk
    name: MobileBomber
  - path: ScriptInterpreter\bin\Release\ScriptInterpreter.dll
    name: ScriptInterpreter